package DAO;

import java.sql.*;
import Model.*;
import Util.ConnectionSingleton;

public class BankUserDAO {

    private static Connection connection = ConnectionSingleton.getConnection();
    /**
     * The user_id is automatically generated by the sql database
     *
     ## Table bank_user (
     user_id int primary key auto_increment,
     username varchar(255) unique,
     password varchar(255)
     );
     *
     */
    public static BankUser insertNewUser(BankUser newBankUser){
        String sql = "INSERT INTO bank_user (username, password) VALUES (?,?);" ;
        try {
            // assuming database automatically generate a primary key.
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // preparedStatement's setString method
            preparedStatement.setString(1, newBankUser.getUsername());
            preparedStatement.setString(2, newBankUser.getPassword());

            preparedStatement.executeUpdate();
            ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys();
            if(pkeyResultSet.next()){
                newBankUser.setUser_id((int)pkeyResultSet.getLong(1));
                return newBankUser;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return null;
    }

    public static BankUser loginUser(BankUser loginUser){
        try {
            String sql = "SELECT * FROM bank_user WHERE username = ? AND password = ?;" ;
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(1, loginUser.getUsername());
            preparedStatement.setString(2, loginUser.getPassword());

            ResultSet rs = preparedStatement.executeQuery();

            while(rs.next()){
                BankUser logedUser = new BankUser(rs.getInt("user_id"),
                        rs.getString("username"),
                        rs.getString("password"));
                return logedUser;
            }

        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return null;
    }
}
