package Model;

/**
 * This is a class that models an Account
 */
public class Account {

    // MAHLET Model, DAO, Service for the Account
    /**
     * an Id for this message will be automatically generated by the database
     */
    private int account_id;
    /**
     * aaccount balance_cents that shows the amount of the user is having in th account
     */
    private long balance_cents;

    private int user;

    public Account() {
    }

    public Account(long balance_cents) {
        this.balance_cents = balance_cents;
    }

    public Account(int account_id, long balance_cents, int user){
        this.account_id = account_id;
        this.balance_cents = balance_cents;
        this.user = user;
    }

    public int getAccount_id() {
        return account_id;
    }

    public void setAccount_id(int account_id) {
        this.account_id = account_id;
    }

    public long getBalance() {
        return balance_cents;
    }

    public void setBalance(long balance_cents) {
        this.balance_cents = balance_cents;
    }

    public int getUser() {
        return user;
    }

    public void setUser(int user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "Account{account_id=" + account_id + ", balance_cents=" + balance_cents + ", user=" + user;
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Account account = (Account)o;
        return account_id == account.account_id && balance_cents == account.balance_cents &&
            user == account.user;
    }
}
