package Model;

/**
 * This is a class that models an Account
 */
public class Account {

    // MAHLET Model, DAO, Service for the Account
    /**
     * an Id for this message will be automatically generated by the database
     */
    private int account_id;
    /**
     * aaccount balance that shows the amount of the user is having in th account
     */
    private double balance;

    private int user;

    public Account(){

    }

    public Account(int account_id, double balance, int user){
        this.account_id = account_id;
        this.balance = balance;
        this.user = user;
    }

    public int getAccount_id() {
        return account_id;
    }

    public void setAccount_id(int account_id) {
        this.account_id = account_id;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public int getUser() {
        return user;
    }

    public void setUser(int user) {
        this.user = user;
    }
}
