package Model;

// FRAN - Model, DAO, Service for the BankUser

public class BankUser {

    /**
     * An id for this user will be automatically generated by the database.
     */
    public int user_id;
    /**
     * A username for this user (must be unique and not blank)
     */
    public String username;
    /**
     * A password for this account (must be over 4 characters)
     */
    public String password;
    /**
     * A default, no-args constructor, as well as correctly formatted getters and setters, are needed for Jackson Objectmapper to work.
     */

    public BankUser(){

    }
    /**
     * When posting a new BankUser, the id can be generated by the database. In that case, a constructor without
     * account_id is needed.
     * @param username
     * @param password
     */
    public BankUser(String username, String password){

    }
    /**
     * Whem retrieving an BankUser from the database, all fields will be needed. In that case, a constructor with all fields is needed.
     * @param user_id
     * @param username
     * @param password
     */
    public BankUser(int user_id, String username, String password) {
        this.user_id = user_id;
        this.username = username;
        this.password = password;
    }

    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return user_id
     */
    public int getUser_id() {
        return user_id;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param user_id
     */
    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return username
     */
    public String getUsername() {
        return username;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return password
     */
    public String getPassword() {
        return password;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Overriding the default equals() method adds functionality to tell when two objects are identical, allowing
     * Assert.assertEquals and List.contains to function.
     * @param o the other object.
     * @return true if o is equal to this object.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BankUser bankUser = (BankUser) o;
        return user_id == bankUser.user_id && username.equals(bankUser.username) && password.equals(bankUser.password);
    }
    /**
     * Overriding the default toString() method allows for easy debugging.
     * @return a String representation of this class.
     */
    @Override
    public String toString() {
        return "Account{" +
                "account_id=" + user_id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

}